Update RHEL789.yml

diff --git a/RHEL789.yml b/RHEL789.yml
--- a/RHEL789.yml
+++ b/RHEL789.yml
@@ -1,5 +1,6 @@
+
 ---
-- name: Detect and Execute RHEL 6 OS-specific tasks
+- name: Detect and Execute RHEL 789 OS-specific tasks
   hosts: all
   gather_facts: yes
   vars:
@@ -28,7 +29,7 @@
       debug:
         var: ansible_distribution_major_version
     
-    - name: Check if user sainath
+    - name: Check if user sainath exists
       shell: getent passwd sainath
       register: check_user
       changed_when: False
@@ -40,43 +41,114 @@
       changed_when: False
       ignore_errors: True      
     
-    - name: Print success message if RHEL 6 server joined domain
-      debug:
-        msg: "RHEL 6 server joined domain"
-      when: check_user.rc == 0 and check_ldap.rc == 0 
-
-    - name: Install realm package and get realm list
+    - name: Install realm package
       shell: |
-            if ! rpm -q realm; then
-            yum install -y realmd || echo "Error: No package realm available"
+            if ! rpm -q realmd; then
+            yum install -y realmd || echo "Error: No package realmd available"
             fi
-            realm list | egrep "realm-name|domain-name"
+      register: check_realmpkg
+      failed_when: "'Error: No package realmd available' in check_realmpkg.stdout"
+
+    - name: Check realm list
+      shell: realm list | egrep "realm-name|domain-name"
       register: check_realm
-      failed_when: "'Error: No package realm available' in check_realm.stdout"
-      
-    - name: Print failure message if RHEL 6 server Not joined domain
+      changed_when: False
+      ignore_errors: True 
+      when: check_realmpkg.stderr == ""
+
+    - name: Print success message if RHEL 789 server joined domain
       debug:
-        msg: "RHEL 6 server Not joined domain"
-      when: check_user.rc != 0 or check_ldap.rc != 0
+        msg: "RHEL 789 server joined domain"
+      when: check_realm.rc == 0
+      
+    - name: Print failure message if RHEL 789 server Not joined domain
+      debug:
+        msg: "RHEL 789 server Not joined domain"
+      when: check_realm.rc != 0
 
-    - name: Exit the playbook if RHEL 6 server joined domain
-      meta: end_play
-      when: check_user.rc == 0 and check_ldap.rc == 0
+    - name: Exit the playbook if RHEL 789 server joined domain
+      fail:
+        msg: "This Server Already Joined Domain."
+      when: check_realm.rc == 0
+      tags: always
 
-    - name: Installing packages in RHEL 6 server
+    - name: Install realm package along with sssd
       package:
         name: "{{ item }}"
         state: latest
       with_items:
+        - realmd
         - adcli
         - sssd
+        - krb5-workstation
         - authconfig
         - oddjob
         - oddjob-mkhomedir
+        - samba-common-tools
         - lsof
-        
-    - name: RHEL 6 server join domain 
-      shell: echo -n "{{password}}" | adcli join {{domain_name}} -U {{username}} -v --stdin-password
+
+    - name: Join domain (RHEL 7, 8, 9)
+      shell: echo "{{password}}" | realm join {{domain_name}} -U sainath --verbose
       register: join_domain
       ignore_errors: yes
-      no_log: True
+
+    - name: Modify SSSD Configuration in RHEL7, 8 and 9
+      copy:
+        src: testfolder/sssd.conf
+        dest: /etc/sssd/
+        mode: "0600"
+
+    - name: Add cert path to the ldap.conf in RHEL7, 8 and 9
+      lineinfile:
+        path: /etc/openldap/ldap.conf
+        insertafter: BOF
+        line: 'TLS_CACERT      /etc/openldap/certs/LDAPS_CERT8.cer'
+        state: present
+
+    - name: start and enable oddjobd.service
+      service:
+        name: oddjobd.service
+        state: started
+        enabled: yes
+    - name: Copy LDAP CERT
+      copy:
+        src: testfolder/LDAPS_CERT8.cer
+        dest: /etc/openldap/certs
+        mode: "0655"
+
+    - name: Restart sssd
+      service:
+        name: sssd
+        state: restarted
+
+    - name: login and print the working directory via ssh
+      shell: id {{username}}
+      register: id
+
+    - name: print the value
+      debug:
+        var: id.stdout_lines
+
+    - name: login Before Blacklisting. (If SSH fails need to validate)
+      shell: sshpass -p "{{password}}" ssh {{username}}@localhost pwd
+      register: ssh
+
+    - name: print the value of login Before Blacklisting
+      debug:
+        var: ssh.stdout_lines
+
+    - name: Blacklisting all Users
+      shell: realm permit -x {{username}}
+
+    - name: Blacklisting all Groups
+      shell: realm permit -xg {{username}}
+
+    - name: login via ssh to user After Blacklisting
+      shell: sshpass -p "{{password}}" ssh {{username}}@localhost pwd
+      register: ssh
+      ignore_errors: yes
+
+    - name: Print message based on SSH exit code (improved)
+      debug:
+        msg: "{{ 'All Users are blacklisted' if ssh.rc == 255 else 'Permission Denied' }}"  # Conditional message
+      when: ssh.rc in (255, 5) and not check_realm.rc == 0 or check_realm.stdout.strip() == ""
