Update test.yaml

diff --git a/test.yaml b/test.yaml
--- a/test.yaml
+++ b/test.yaml
@@ -1,31 +1,64 @@
 ---
-- name: Check if machine is joined to AD domain
+- name: Detect and Execute RHEL 6 OS-specific tasks
   hosts: all
   gather_facts: yes
-  become: true
+  vars:
+    domain_name: "wikilab.asia"
+    username: "sainath@wikilab.asia"
+    password: "Redhat123"
 
   tasks:
-  - name: Check if user exists
-    command: id sainath
-    register: user_check
-    changed_when: False
-    ignore_errors: True
-    
-  - name: Print user_check result
-    debug:
-      msg: "Output of 'id sainath': {{ user_check.stdout }}"
-    
-  - name: Check if LDAP port is in use
-    command: lsof -i:636
-    register: ldap_check
-    changed_when: False
-    ignore_errors: True
-
-  - name: Print ldap_check result
-    debug:
-      msg: "Output of 'lsof -i:636': {{ ldap_check.stdout }}"
-  - name: Print result
   
-    debug:
-      msg: "Machine is joined to AD domain"
-    when: user_check.stdout != "" and ldap_check.stdout != ""
+    - name: Check if running on RHEL 789
+      fail:
+        msg: "This playbook only runs on RHEL 789 servers."
+      when: ansible_distribution_major_version | int == 6
+      tags: always
+      
+    - name: Gather OS version and distribution facts
+      debug:
+        var: ansible_distribution_version
+      register: os_version
+
+    - name: Extract OS major version from facts
+      set_fact:
+        ansible_distribution_major_version: "{{ ansible_distribution_version.split('.')[0] }}"
+
+    - name: Print the OS major version
+      debug:
+        var: ansible_distribution_major_version
+    
+    - name: Check if user sainath exists in RHEL6
+      shell: getent passwd sainath
+      register: check_user
+      changed_when: False
+      ignore_errors: True
+      
+    - name: Check if LDAP port is in use
+      shell: lsof -i:636
+      register: check_ldap
+      changed_when: False
+      ignore_errors: True      
+    
+    - name: Print success message if RHEL 6 server joined domain
+      debug:
+        msg: "RHEL 6 server joined domain"
+      when: check_user.rc == 0 and check_ldap.rc == 0 
+
+    - name: Install realm package and get realm list
+      shell: |
+            if ! rpm -q realm; then
+            yum install -y realmd || echo "Error: No package realm available"
+            fi
+            realm list | egrep "realm-name|domain-name"
+      register: check_realm
+      failed_when: "'Error: No package realm available' in check_realm.stdout"
+      
+    - name: Print failure message if RHEL 6 server Not joined domain
+      debug:
+        msg: "RHEL 6 server Not joined domain"
+      when: check_user.rc != 0 or check_ldap.rc != 0
+
+    - name: Exit the playbook if RHEL 6 server joined domain
+      meta: end_play
+      when: check_user.rc == 0 and check_ldap.rc == 0
